services:
   namenode:
      image: apache/hadoop:3.4.1
      container_name: namenode
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      environment:
#        - ENSURE_NAMENODE_DIR="/tmp/hadoop-hadoop/dfs/name" # For first start to format dfs
        - HADOOP_HOME=/opt/hadoop
        - CORE-SITE.XML_fs.default.name=hdfs://namenode
        - CORE-SITE.XML_fs.defaultFS=hdfs://namenode
        - HDFS-SITE.XML_dfs.namenode.rpc-address=namenode:8020
        - HDFS-SITE.XML_dfs.replication=3
      volumes:
        - ./data/namenode:/tmp/hadoop-hadoop/dfs/name

   datanode1:
      image: apache/hadoop:3.4.1
      container_name: datanode1
      hostname: datanode1
      command: ["hdfs", "datanode"]
      ports:
        - 9864:9864
      environment:
        - HADOOP_HOME=/opt/hadoop
        - CORE-SITE.XML_fs.default.name=hdfs://namenode
        - CORE-SITE.XML_fs.defaultFS=hdfs://namenode
        - HDFS-SITE.XML_dfs.namenode.rpc-address=namenode:8020
        - HDFS-SITE.XML_dfs.replication=3
      volumes:
        - ./data/datanode1:/tmp/hadoop-hadoop/dfs/data

   datanode2:
      image: apache/hadoop:3.4.1
      container_name: datanode2
      hostname: datanode2
      command: ["hdfs", "datanode"]
      ports:
        - 9865:9864
      environment:
        - HADOOP_HOME=/opt/hadoop
        - CORE-SITE.XML_fs.default.name=hdfs://namenode
        - CORE-SITE.XML_fs.defaultFS=hdfs://namenode
        - HDFS-SITE.XML_dfs.namenode.rpc-address=namenode:8020
        - HDFS-SITE.XML_dfs.replication=3
      volumes:
        - ./data/datanode2:/tmp/hadoop-hadoop/dfs/data

   datanode3:
      image: apache/hadoop:3.4.1
      container_name: datanode3
      hostname: datanode3
      command: ["hdfs", "datanode"]
      ports:
        - 9866:9864
      environment:
        - HADOOP_HOME=/opt/hadoop
        - CORE-SITE.XML_fs.default.name=hdfs://namenode
        - CORE-SITE.XML_fs.defaultFS=hdfs://namenode
        - HDFS-SITE.XML_dfs.namenode.rpc-address=namenode:8020
        - HDFS-SITE.XML_dfs.replication=3
      volumes:
        - ./data/datanode3:/tmp/hadoop-hadoop/dfs/data
